### PR TITLE
WIP: Helix editor theme

### PR DESCRIPTION
**Pull request by zoedsoupe**
Introducing a initial version of the [helix](https://helix-editor.com)!

SCR-20240623-nbxr-2

### CODE REVIEW

**Comment by raphamorim** [comment]
👏

**Comment by raphamorim** [comment]
@zoedsoupe is ready to review?

**Review by raphamorim — APPROVED** [review]
I tested locally and worked fine, merging it! thank you @zoedsoupe

**Comment by zoedsoupe** [comment]
i just checked the notification right now. ty for testing it locally! i tried to follow strictly the color palette and highlight semantics but i think there're one or another semantic that helix is missing. does you missed any color in particular? i mostly test with elixir/rust code

**Pull request merged**
