### PR TITLE
Refactored project to fit atom conventions 

### PR DESCRIPTION
**Pull request by t4r0**
also a more readable less file and updated to fit the atom 1.0 APIs

### CODE REVIEW

**Comment by raphamorim** [comment]
Good!

It is working very well. But It's changing the color of configuration items

Example: 
screen shot 2015-06-30 at 3 57 29 pm

**Comment by raphamorim** [comment]
Both the menu and the heading

**Comment by t4r0** [comment]
Ok I'll fix it.

**Comment by raphamorim** [comment]
@t4r0 Good job!

**Comment by t4r0** [comment]
Thanks @raphamorim

**Pull request merged**
