### PR TITLE
Xcode Lucario Theme

### PR DESCRIPTION
**Pull request by ezefranca**

### CODE REVIEW

**Comment by raphamorim** [comment]
Ow! awesome, i've think about this in these days.

@ezefranca can you update the docs? :)

**Comment by ezefranca** [comment]
@raphamorim sure!

**Comment by raphamorim** [comment]
I could not wait to use in my Xcode. So I finished by another PR.

Thanks for your time and contribution :)

**Comment by ezefranca** [comment]
@raphamorim sorry, i really forget ... :(  thanks :+1:

**Comment by raphamorim** [comment]
No problem @ezefranca.

I confess that I forgot too hehe. Thanks for the contribuition :octocat:

**Pull request merged**
